name: Environment Variables
env:
  WORKSPACE_ENVIRONMENT_VARIABLE: 'custom workspace environment variable'
  OVER_RIDE: 'Workflow'
on: [push]
jobs:
  ubuntu:
    env:
      JOB_ENVIRONMENT_VARIABLE: 'custom job environment variable for ubuntu'
      OVER_RIDE: 'Job'
    runs-on: ubuntu-latest
    steps:
      - name: Print custom environment variables from ubuntu-latest
        env:
          STEP_ENVIRONMENT_VARIABLE: 'custom step environment variable for bash'
          OVER_RIDE: 'STEP'
        run: |
          echo "Accessing environment variables in run command"
          echo "$WORKSPACE_ENVIRONMENT_VARIABLE"
          echo "$JOB_ENVIRONMENT_VARIABLE"
          echo "$STEP_ENVIRONMENT_VARIABLE"
          echo "------------------------------------------------------"
          echo "Accessing environment variables using env context"
          echo "${{ env.WORKSPACE_ENVIRONMENT_VARIABLE }}"
          echo "${{ env.JOB_ENVIRONMENT_VARIABLE }}"
          echo "${{ env.STEP_ENVIRONMENT_VARIABLE }} Not defined"
  windows:
    env:
      JOB_ENVIRONMENT_VARIABLE: 'custom job environment variable for windows'
      OVER_RIDE: 'Job'
    runs-on: windows-latest
    steps:
      - name: Print custom environment variables from windows-latest
        env:
          STEP_ENVIRONMENT_VARIABLE: 'custom step environment variable for powershell'
          OVER_RIDE: 'STEP'
        run: |
          echo "Accessing environment variables in run command"
          echo "$Env:WORKSPACE_ENVIRONMENT_VARIABLE"
          echo "$Env:JOB_ENVIRONMENT_VARIABLE"
          echo "$Env:STEP_ENVIRONMENT_VARIABLE"
          echo "------------------------------------------------------"
          echo "Accessing environment variables using env context"
          echo "${{ env.WORKSPACE_ENVIRONMENT_VARIABLE }}"
          echo "${{ env.JOB_ENVIRONMENT_VARIABLE }}"
          echo "${{ env.STEP_ENVIRONMENT_VARIABLE }} Not defined"
